### PR TITLE
Add a JPMS module-info and fix some javadoc warning due to missing ja…

### PR DESCRIPTION
**Pull request by starksm64**
…karta.annotation dependency
#308 

Signed-off-by: Scott M Stark <starksm64@gmail.com>

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]
Okay, although can't/shouldn't we just move the entire API to JDK 11?

**Comment by starksm64** [comment]
I did not know if that is what was desired. I can make that change if you want.

**Comment by starksm64** [comment]
I have updated the source/target to Java 11

**Comment by arjantijms** [comment]
Thanks @starksm64

**Comment by pzygielo** [comment]
May I ask to have https://ci.eclipse.org/messaging/job/messaging-master-build/ (+probably more) updated to use Java11 accordingly?

**Comment by arjantijms** [comment]
> May I ask to have https://ci.eclipse.org/messaging/job/messaging-master-build/ (+probably more) updated to use Java11 accordingly?

It is done, thx!

**Pull request merged**
