### PR TITLE
Set target release with property

### PR DESCRIPTION
**Pull request by pzygielo**
This property is also used by javadoc plugin.

### CODE REVIEW

**Comment by pzygielo** [comment]
May I ask for review, please?

**Review by arjantijms — APPROVED** [review]
No problem with the change itself, but messaging is now the only one that has this as a property. We should strive to keep the poms for all APIs in Jakarta EE reasonably consistent.

**Comment by pzygielo** [comment]
Thanks for checking.

1. This property is shared by https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#release and https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#release

2. Currently generated javadocs link to https://docs.oracle.com/en/java/javase/8/docs/api/, per https://github.com/jakartaee/messaging/blob/a59f98b45372f83447778ea22a7fc67797292e23/api/pom.xml#L218

3. I think the above configuration could be dropped if this property should be used. Will rebase this PR and modify plugin config.

**Comment by pzygielo** [comment]
> We should strive to keep the poms for all APIs in Jakarta EE reasonably consistent.

It's still undecided to do on the parent level:
- eclipse-ee4j/ee4j#68

> but messaging is now the only one that has this as a property. 

Not sure what you mean by that, for example: https://github.com/jakartaee/enterprise-beans/blob/8c2c5c3a8fc438fff0a46aef174cc658c96f256b/api/pom.xml#L39

**Comment by OndroMih** [comment]
I think that until it's decided on the parent level, it's OK to specify this in Messaging. The API now requires Java 11 (see https://github.com/jakartaee/messaging/pull/309 and https://github.com/jakartaee/messaging/pull/313), so it's fine to set it in pom too.

I'm approving and will merge.

**Review by OndroMih — APPROVED** [review]

**Pull request merged**
